[package]
name = "wrapper_with_default"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.100"
