name: test-extended-label

on:
  pull_request:
    types: [ opened, synchronize, labeled ] # Also trigger when adding labels
  merge_group:

permissions:
  contents: read

# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:

  k8s-e2e-tests-extended:
    if: contains(github.event.pull_request.labels.*.name, 'k8s-extended-e2e')
    uses: ./.github/workflows/component_k8s_e2e.yml
    with:
      scenarios: '["apm", "collector", "ebpf", "dynamic", "custom-repo", "fleet-control", "proxy"]'
      # Network policies needs calico installed, the others do not
      minikube_start_args: '--cni=calico'
    secrets:
      NR_SYSTEM_IDENTITY_CLIENT_ID: ${{ secrets.AC_PROD_E2E_NR_SYSTEM_IDENTITY_CLIENT_ID }}
      NR_SYSTEM_IDENTITY_PRIVATE_KEY: ${{ secrets.AC_PROD_E2E_NR_SYSTEM_IDENTITY_PRIVATE_KEY }}
      E2E_ACCOUNT_ID: ${{ secrets.AC_PROD_E2E_ACCOUNT_ID }}
      E2E_API_KEY: ${{ secrets.AC_PROD_E2E_API_KEY }}
      E2E_LICENSE_KEY: ${{ secrets.AC_PROD_E2E_LICENSE_KEY }}

  onhost-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'onhost-extended-e2e')
    uses: ./.github/workflows/component_onhost_e2e.yaml
    secrets:
      NR_SYSTEM_IDENTITY_CLIENT_ID: ${{ secrets.AC_PROD_E2E_NR_SYSTEM_IDENTITY_CLIENT_ID }}
      NR_SYSTEM_IDENTITY_PRIVATE_KEY: ${{ secrets.AC_PROD_E2E_NR_SYSTEM_IDENTITY_PRIVATE_KEY }}
      E2E_ACCOUNT_ID: ${{ secrets.AC_PROD_E2E_ACCOUNT_ID }}
      E2E_API_KEY: ${{ secrets.AC_PROD_E2E_API_KEY }}
      E2E_LICENSE_KEY: ${{ secrets.AC_PROD_E2E_LICENSE_KEY }}
