name: ðŸ¤ Plan k8s canaries infrastructure changes

on:
  pull_request:
    paths:
      - test/k8s-canaries/terraform/**

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: false

jobs:
  infra:
    name: Prepare infra
    runs-on: linux-4-core-nr-control
    permissions:
      # required to oidc AWS
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          # Is the ref a tag? If so, remove refs/tags/ prefix
          GIT_BRANCH="${GIT_BRANCH#refs/tags/}"
          echo "GIT_BRANCH=$GIT_BRANCH" >> "$GITHUB_ENV"

      - name: Plan k8s staging canary changes
        uses: newrelic/fargate-runner-action@main
        with:
          aws_region: us-east-2
          container_make_target: "TERRAFORM_DIR=test/k8s-canaries/terraform CANARY_DIR=staging test/k8s-canaries/terraform-plan"
          ecs_cluster_name: agent_control
          task_definition_name: agent_control
          cloud_watch_logs_group_name: /ecs/test-prerelease-agent_control
          cloud_watch_logs_stream_name: ecs/test-agent_control
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          repo_name: ${{ github.repository }}
          git_clone_url: "ssh://git@github.com/${{ github.repository }}.git"
          ref: "${{ env.GIT_BRANCH }}"

      - name: Plan k8s production canary changes
        uses: newrelic/fargate-runner-action@main
        with:
          aws_region: us-east-2
          container_make_target: "TERRAFORM_DIR=test/k8s-canaries/terraform CANARY_DIR=production test/k8s-canaries/terraform-plan"
          ecs_cluster_name: agent_control
          task_definition_name: agent_control
          cloud_watch_logs_group_name: /ecs/test-prerelease-agent_control
          cloud_watch_logs_stream_name: ecs/test-agent_control
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          repo_name: ${{ github.repository }}
          git_clone_url: "ssh://git@github.com/${{ github.repository }}.git"
          ref: "${{ env.GIT_BRANCH }}"
